typealias List[A] = @immut/list.T[A]

typealias Buffer = @buffer.Buffer

typealias Indent = @marbit_base.Indent

typealias Meta = @marbit_base.Meta

typealias TextLoc = @marbit_base.TextLoc

typealias LinePos = @marbit_base.LinePos

typealias BytePos = @marbit_base.BytePos

typealias FilePath = @marbit_base.FilePath

let file_path_none = @marbit_base.file_path_none

typealias Span = @marbit_base.Span

typealias LineSpan = @marbit_base.LineSpan

typealias RevSpans = @marbit_base.RevSpans

typealias HeadingLevel = @marbit_base.HeadingLevel

typealias NextLineFn[A] = @marbit_base.NextLineFn[A]

typealias HtmlBlockEndCond = @marbit_base.HtmlBlockEndCond

typealias ListType = @marbit_base.ListType

typealias LineType = @marbit_base.LineType
